### ISSUE TITLE
Can't write to Blob

### ISSUE THREAD

**Issue by tdbs** [michiya/azure-storage-logging#1]
I tried this, and no container is created, not even when the container exists, nothing happens.

```
LOGGING = {
    'version': 1,
    'formatters': {
        'simple': {
            'format': '%(asctime)s %(message)s',
        },
        'verbose': {
            'format': '%(asctime)s %(levelname)s %(hostname)s %(process)d %(message)s',
        }
    },
    'handlers': {
        'file': {
            'account_name': 'myaccountname',
            'account_key': 'myaccountkey',
            'protocol': 'https',
            'level': 'DEBUG',
            'class': 'azure_storage_logging.handlers.BlobStorageTimedRotatingFileHandler',
            'formatter': 'verbose',
            'filename': 'example.log',
            'when': 'D',
            'interval': 1,
            'container': 'logs-%(hostname)s',
            'zip_compression': False,
        }
    },
    'root': {
        'handlers': ['file'],
        'level': 'DEBUG',
    }
}

import logging
from logging.config import dictConfig
# from azure_storage_logging.handlers import BlobStorageTimedRotatingFileHandler

try:
    dictConfig(LOGGING)
except:
    print 'Error Loading Config'
else: print 'Config Loaded'
```

**Comment by tdbs** [comment]
It does create a local file example.log instead of on the cloud storage

**Comment by michiya** [comment]
The handler tries to store a log file in a blob container when the log file is outdated, and the handler creates the container at the same time if it doesn't exist in your storage.

The handler also evaluates if the log file should be rolled over or not when logging is performed, so add some logging to the file at the last of your example like the following and run it once.

```
logging.getLogger('root').info('test message')
```

And then run the example again after 24 hours or more (because the interval is set to 1 day in the example), and the container will be created in your storage and the outdated log file will be stored in the container.

**Comment by tdbs** [comment]
Ok, i misunderstood and thought the file would be created instantly, and not only when the log file is outdated. You can close the issue sorry.
